"""Initial migration

Revision ID: b0655850fcf0
Revises: 
Create Date: 2026-01-15 17:47:15.974033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0655850fcf0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_admin_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_password_hash'), ['password_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_phone'), ['phone'], unique=True)

    op.create_table('waiting_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('waiting_list', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_waiting_list_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_waiting_list_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_waiting_list_phone'), ['phone'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waiting_list', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waiting_list_phone'))
        batch_op.drop_index(batch_op.f('ix_waiting_list_id'))
        batch_op.drop_index(batch_op.f('ix_waiting_list_email'))

    op.drop_table('waiting_list')
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_phone'))
        batch_op.drop_index(batch_op.f('ix_admin_password_hash'))
        batch_op.drop_index(batch_op.f('ix_admin_id'))
        batch_op.drop_index(batch_op.f('ix_admin_email'))

    op.drop_table('admin')
    # ### end Alembic commands ###
